# CMake generated Testfile for 
# Source directory: /root/simgrid/simgrid
# Build directory: /root/simgrid/simgrid
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(tesh-self-basic "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/bin" "--cd" "/root/simgrid/simgrid/tools/tesh" "basic.tesh")
ADD_TEST(tesh-self-cd "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/bin" "/root/simgrid/simgrid/tools/tesh/cd.tesh")
ADD_TEST(tesh-self-IO-broken-pipe "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/tools/tesh" "IO-broken-pipe.tesh")
ADD_TEST(tesh-self-IO-orders "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/bin" "/root/simgrid/simgrid/tools/tesh/IO-orders.tesh")
ADD_TEST(tesh-self-IO-bigsize "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/tools/tesh" "IO-bigsize.tesh")
ADD_TEST(tesh-self-set-return "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/tools/tesh" "set-return.tesh")
ADD_TEST(tesh-self-set-timeout "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/tools/tesh" "set-timeout.tesh")
ADD_TEST(tesh-self-set-ignore-output "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/bin" "/root/simgrid/simgrid/tools/tesh/set-ignore-output.tesh")
ADD_TEST(tesh-self-catch-return "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/bin" "/root/simgrid/simgrid/tools/tesh/catch-return.tesh")
ADD_TEST(tesh-self-catch-timeout "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/bin" "/root/simgrid/simgrid/tools/tesh/catch-timeout.tesh")
ADD_TEST(tesh-self-catch-wrong-output "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/bin" "/root/simgrid/simgrid/tools/tesh/catch-wrong-output.tesh")
ADD_TEST(tesh-self-bg-basic "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/tools/tesh" "bg-basic.tesh")
ADD_TEST(tesh-self-background "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/tools/tesh" "background.tesh")
ADD_TEST(tesh-self-set-signal "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/tools/tesh" "set-signal.tesh")
ADD_TEST(tesh-self-bg-set-signal "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/tools/tesh" "bg-set-signal.tesh")
ADD_TEST(tesh-self-catch-signal "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/bin" "/root/simgrid/simgrid/tools/tesh/catch-signal.tesh")
ADD_TEST(help "/root/simgrid/simgrid/teshsuite/simdag/platforms/basic_parsing_test" "--help")
ADD_TEST(help-models "/root/simgrid/simgrid/teshsuite/simdag/platforms/basic_parsing_test" "--help-models")
ADD_TEST(xbt-log-large "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/xbt/log_large_test.tesh")
ADD_TEST(xbt-log-parallel "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/xbt/parallel_log_crashtest.tesh")
ADD_TEST(xbt-mmalloc-64 "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/xbt/mmalloc_64.tesh")
ADD_TEST(xbt-parmap "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/xbt/parmap_test.tesh")
ADD_TEST(simix_factory_default "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simix/factory_raw.tesh")
ADD_TEST(simix_factory_thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simix/factory_thread.tesh")
ADD_TEST(simix_factory_raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simix/factory_raw.tesh")
ADD_TEST(simix_factory_ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simix/factory_ucontext.tesh")
ADD_TEST(tesh-msg-get-sender-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/msg/get_sender.tesh")
ADD_TEST(tesh-msg-get-sender-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/msg/get_sender.tesh")
ADD_TEST(tesh-msg-get-sender-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/msg/get_sender.tesh")
ADD_TEST(tesh-msg-pid-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/msg/pid.tesh")
ADD_TEST(tesh-msg-pid-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/msg/pid.tesh")
ADD_TEST(tesh-msg-pid-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/msg/pid.tesh")
ADD_TEST(tesh-simdag-parser-bogus-symmetric "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/simdag/platforms" "--cd" "/root/simgrid/simgrid/teshsuite/simdag/platforms" "two_hosts_asymetric.tesh")
ADD_TEST(tesh-simdag-bypass "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/simdag/platforms" "--setenv" "srcdir=/root/simgrid/simgrid" "--cd" "/root/simgrid/simgrid/teshsuite/simdag/platforms" "basic_parsing_test_bypass.tesh")
ADD_TEST(tesh-simdag-flatifier "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/simdag/platforms" "--setenv" "srcdir=/root/simgrid/simgrid" "--cd" "/root/simgrid/simgrid/teshsuite/simdag/platforms" "flatifier.tesh")
ADD_TEST(tesh-simdag-link "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/simdag/platforms" "--setenv" "srcdir=/root/simgrid/simgrid" "--cd" "/root/simgrid/simgrid/teshsuite/simdag/platforms" "basic_link_test.tesh")
ADD_TEST(tesh-simdag-reinit-costs "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/network/test_reinit_costs.tesh")
ADD_TEST(tesh-simdag-parser "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/simdag/platforms" "--cd" "/root/simgrid/simgrid/teshsuite/simdag/platforms" "basic_parsing_test.tesh")
ADD_TEST(tesh-simdag-parser-sym-full "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/simdag/platforms" "--cd" "/root/simgrid/simgrid/teshsuite/simdag/platforms" "basic_parsing_test_sym_full.tesh")
ADD_TEST(tesh-simdag-full-links "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/simdag/platforms" "--cd" "/root/simgrid/simgrid/teshsuite/simdag/platforms" "get_full_link.tesh")
ADD_TEST(tesh-simdag-basic0 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/basic0.tesh")
ADD_TEST(tesh-simdag-basic1 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/basic1.tesh")
ADD_TEST(tesh-simdag-basic2 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/basic2.tesh")
ADD_TEST(tesh-simdag-basic3 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/basic3.tesh")
ADD_TEST(tesh-simdag-basic4 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/basic4.tesh")
ADD_TEST(tesh-simdag-basic5 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/basic5.tesh")
ADD_TEST(tesh-simdag-basic6 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/basic6.tesh")
ADD_TEST(tesh-simdag-incomplete "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/incomplete.tesh")
ADD_TEST(tesh-simdag-p2p-1 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/network/p2p/test_latency1.tesh")
ADD_TEST(tesh-simdag-p2p-2 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/network/p2p/test_latency2.tesh")
ADD_TEST(tesh-simdag-p2p-3 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/network/p2p/test_latency3.tesh")
ADD_TEST(tesh-simdag-p2p-4 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/network/p2p/test_latency_bound.tesh")
ADD_TEST(tesh-simdag-mxn-1 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/network/mxn/test_intra_all2all.tesh")
ADD_TEST(tesh-simdag-mxn-2 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/network/mxn/test_intra_independent_comm.tesh")
ADD_TEST(tesh-simdag-mxn-3 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/network/mxn/test_intra_scatter.tesh")
ADD_TEST(tesh-simdag-par-1 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/partask/test_comp_only_seq.tesh")
ADD_TEST(tesh-simdag-par-2 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/partask/test_comp_only_par.tesh")
ADD_TEST(tesh-simdag-availability "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/simdag/availability/availability_test.tesh")
ADD_TEST(msg-file "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/" "--setenv" "srcdir=/root/simgrid/simgrid/" "--cd" "/root/simgrid/simgrid/examples/" "/root/simgrid/simgrid/examples/msg/io/io.tesh")
ADD_TEST(msg-start-kill-time "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/" "--setenv" "srcdir=/root/simgrid/simgrid/" "--cd" "/root/simgrid/simgrid/examples/" "/root/simgrid/simgrid/examples/msg/start_kill_time/start_kill_time.tesh")
ADD_TEST(msg-chainsend "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chainsend" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg/chainsend" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/chainsend/chainsend.tesh")
ADD_TEST(msg-sendrecv-CLM03-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/sendrecv/sendrecv_CLM03.tesh")
ADD_TEST(msg-sendrecv-Vegas-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/sendrecv/sendrecv_Vegas.tesh")
ADD_TEST(msg-sendrecv-Reno-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/sendrecv/sendrecv_Reno.tesh")
ADD_TEST(msg-suspend-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/suspend/suspend.tesh")
ADD_TEST(msg-pmm-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/pmm/pmm.tesh")
ADD_TEST(msg-masterslave-bypass-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_bypass.tesh")
ADD_TEST(msg-masterslave-kill-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_kill.tesh")
ADD_TEST(msg-masterslave-multicore-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_multicore.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-mailbox-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_mailbox.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-forwarder-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_forwarder.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-failure-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_failure.tesh")
ADD_TEST(msg-masterslave-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_crosstraffic.tesh")
ADD_TEST(msg-masterslave-forwarder-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_forwarder_crosstraffic.tesh")
ADD_TEST(msg-masterslave-failure-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_failure_crosstraffic.tesh")
ADD_TEST(msg-masterslave-mailbox-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_mailbox_crosstraffic.tesh")
ADD_TEST(msg-masterslave-cpu-ti-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/masterslave" "--cd" "/root/simgrid/simgrid/examples/msg" "masterslave/masterslave_cpu_ti_crosstraffic.tesh")
ADD_TEST(msg-masterslave-virtual-machines "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/cloud/masterslave_virtual_machines.tesh")
ADD_TEST(msg-energy-pstates "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e1/pstate.tesh")
ADD_TEST(msg-energy-consumption "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e2/energy_consumption.tesh")
ADD_TEST(msg-energy-concurrent-tasks "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e3/concurrent_tasks.tesh")
ADD_TEST(msg-storage "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/teshsuite" "--cd" "/root/simgrid/simgrid/teshsuite" "/root/simgrid/simgrid/teshsuite/msg/storage/storage.tesh")
ADD_TEST(msg-cloud-simple-vm-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/cloud/" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg/cloud/" "--cd" "/root/simgrid/simgrid/examples/msg/cloud/" "/root/simgrid/simgrid/examples/msg/cloud/simple_vm.tesh")
ADD_TEST(msg-sendrecv-CLM03-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/sendrecv/sendrecv_CLM03.tesh")
ADD_TEST(msg-sendrecv-Vegas-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/sendrecv/sendrecv_Vegas.tesh")
ADD_TEST(msg-sendrecv-Reno-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/sendrecv/sendrecv_Reno.tesh")
ADD_TEST(msg-suspend-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/suspend/suspend.tesh")
ADD_TEST(msg-pmm-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/pmm/pmm.tesh")
ADD_TEST(msg-masterslave-bypass-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_bypass.tesh")
ADD_TEST(msg-masterslave-kill-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_kill.tesh")
ADD_TEST(msg-masterslave-multicore-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_multicore.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-mailbox-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_mailbox.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-forwarder-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_forwarder.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-failure-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_failure.tesh")
ADD_TEST(msg-masterslave-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_crosstraffic.tesh")
ADD_TEST(msg-masterslave-forwarder-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_forwarder_crosstraffic.tesh")
ADD_TEST(msg-masterslave-failure-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_failure_crosstraffic.tesh")
ADD_TEST(msg-masterslave-mailbox-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_mailbox_crosstraffic.tesh")
ADD_TEST(msg-masterslave-cpu-ti-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/masterslave" "--cd" "/root/simgrid/simgrid/examples/msg" "masterslave/masterslave_cpu_ti_crosstraffic.tesh")
ADD_TEST(msg-energy-pstates-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e1/pstate.tesh")
ADD_TEST(msg-energy-consumption-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e2/energy_consumption.tesh")
ADD_TEST(msg-energy-concurrent-tasks-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e3/concurrent_tasks.tesh")
ADD_TEST(msg-masterslave-virtual-machines-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/cloud/masterslave_virtual_machines.tesh")
ADD_TEST(msg-cloud-two-tasks-vm-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/cloud/" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg/cloud/" "--cd" "/root/simgrid/simgrid/examples/msg/cloud/" "/root/simgrid/simgrid/examples/msg/cloud/two_tasks_vm.tesh")
ADD_TEST(msg-cloud-simple-vm-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/cloud/" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg/cloud/" "--cd" "/root/simgrid/simgrid/examples/msg/cloud/" "/root/simgrid/simgrid/examples/msg/cloud/simple_vm.tesh")
ADD_TEST(msg-sendrecv-CLM03-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/sendrecv/sendrecv_CLM03.tesh")
ADD_TEST(msg-sendrecv-Vegas-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/sendrecv/sendrecv_Vegas.tesh")
ADD_TEST(msg-sendrecv-Reno-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/sendrecv/sendrecv_Reno.tesh")
ADD_TEST(msg-suspend-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/suspend/suspend.tesh")
ADD_TEST(msg-pmm-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/pmm/pmm.tesh")
ADD_TEST(msg-masterslave-bypass-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_bypass.tesh")
ADD_TEST(msg-masterslave-kill-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_kill.tesh")
ADD_TEST(msg-masterslave-multicore-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_multicore.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-mailbox-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_mailbox.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-forwarder-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_forwarder.tesh")
ADD_TEST(msg-masterslave-no-crosstraffic-failure-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_failure.tesh")
ADD_TEST(msg-masterslave-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_crosstraffic.tesh")
ADD_TEST(msg-masterslave-forwarder-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_forwarder_crosstraffic.tesh")
ADD_TEST(msg-masterslave-failure-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_failure_crosstraffic.tesh")
ADD_TEST(msg-masterslave-mailbox-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_mailbox_crosstraffic.tesh")
ADD_TEST(msg-masterslave-cpu-ti-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/masterslave" "--cd" "/root/simgrid/simgrid/examples/msg" "masterslave/masterslave_cpu_ti_crosstraffic.tesh")
ADD_TEST(msg-masterslave-vivaldi-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_vivaldi.tesh")
ADD_TEST(msg-masterslave-virtual-machines-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/cloud/masterslave_virtual_machines.tesh")
ADD_TEST(msg-cloud-two-tasks-vm-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/cloud/" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg/cloud/" "--cd" "/root/simgrid/simgrid/examples/msg/cloud/" "/root/simgrid/simgrid/examples/msg/cloud/two_tasks_vm.tesh")
ADD_TEST(msg-cloud-simple-vm-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/cloud/" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg/cloud/" "--cd" "/root/simgrid/simgrid/examples/msg/cloud/" "/root/simgrid/simgrid/examples/msg/cloud/simple_vm.tesh")
ADD_TEST(msg-energy-pstates-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e1/pstate.tesh")
ADD_TEST(msg-energy-consumption-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e2/energy_consumption.tesh")
ADD_TEST(msg-energy-concurrent-tasks-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e3/concurrent_tasks.tesh")
ADD_TEST(msg-energy-pstates-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e1/pstate.tesh")
ADD_TEST(msg-energy-consumption-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e2/energy_consumption.tesh")
ADD_TEST(msg-energy-concurrent-tasks-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/energy/e3/concurrent_tasks.tesh")
ADD_TEST(msg-masterslave-vivaldi-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_vivaldi.tesh")
ADD_TEST(msg-token-ring-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid" "--cd" "/root/simgrid/simgrid/examples/msg/token_ring" "/root/simgrid/simgrid/examples/msg/token_ring/token_ring.tesh")
ADD_TEST(msg-token-ring-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid" "--cd" "/root/simgrid/simgrid/examples/msg/token_ring" "/root/simgrid/simgrid/examples/msg/token_ring/token_ring.tesh")
ADD_TEST(msg-masterslave-vivaldi-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/masterslave/masterslave_vivaldi.tesh")
ADD_TEST(msg-token-ring-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid" "--cd" "/root/simgrid/simgrid/examples/msg/token_ring" "/root/simgrid/simgrid/examples/msg/token_ring/token_ring.tesh")
ADD_TEST(msg-migration-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/migration/migration.tesh")
ADD_TEST(msg-ptask-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/parallel_task/parallel_task.tesh")
ADD_TEST(msg-priority-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/priority/priority.tesh")
ADD_TEST(msg-properties-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/properties/msg_prop.tesh")
ADD_TEST(msg-icomms-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg/icomms" "--cd" "/root/simgrid/simgrid/examples/msg/icomms" "/root/simgrid/simgrid/examples/msg/icomms/peer.tesh")
ADD_TEST(msg-actions-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/actions" "--cd" "/root/simgrid/simgrid/examples/msg/actions" "actions.tesh")
ADD_TEST(msg-trace-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/msg" "--cd" "/root/simgrid/simgrid/teshsuite/msg" "trace/trace.tesh")
ADD_TEST(msg-chord-no-crosstraffic-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord.tesh")
ADD_TEST(msg-chord-no-crosstraffic-thread-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cfg" "contexts/nthreads:4" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord.tesh")
ADD_TEST(msg-chord-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord_crosstraffic.tesh")
ADD_TEST(msg-chord-thread-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cfg" "contexts/nthreads:4" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord_crosstraffic.tesh")
ADD_TEST(msg-bittorrent-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/bittorrent" "--cd" "/root/simgrid/simgrid/examples/msg/bittorrent" "bittorrent.tesh")
ADD_TEST(msg-bittorrent-thread-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/nthreads:4" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/bittorrent" "--cd" "/root/simgrid/simgrid/examples/msg/bittorrent" "bittorrent.tesh")
ADD_TEST(msg-kademlia-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/kademlia" "--cd" "/root/simgrid/simgrid/examples/msg/kademlia" "kademlia.tesh")
ADD_TEST(msg-kademlia-thread-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/nthreads:4" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/kademlia" "--cd" "/root/simgrid/simgrid/examples/msg/kademlia" "kademlia.tesh")
ADD_TEST(msg-migration-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/migration/migration.tesh")
ADD_TEST(msg-ptask-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/parallel_task/parallel_task.tesh")
ADD_TEST(msg-priority-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/priority/priority.tesh")
ADD_TEST(msg-properties-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/properties/msg_prop.tesh")
ADD_TEST(msg-icomms-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg/icomms" "--cd" "/root/simgrid/simgrid/examples/msg/icomms" "/root/simgrid/simgrid/examples/msg/icomms/peer.tesh")
ADD_TEST(msg-actions-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/actions" "--cd" "/root/simgrid/simgrid/examples/msg/actions" "actions.tesh")
ADD_TEST(msg-trace-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/msg" "--cd" "/root/simgrid/simgrid/teshsuite/msg" "trace/trace.tesh")
ADD_TEST(msg-chord-no-crosstraffic-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord.tesh")
ADD_TEST(msg-chord-no-crosstraffic-ucontext-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cfg" "contexts/nthreads:4" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord.tesh")
ADD_TEST(msg-chord-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord_crosstraffic.tesh")
ADD_TEST(msg-chord-ucontext-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cfg" "contexts/nthreads:4" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord_crosstraffic.tesh")
ADD_TEST(msg-bittorrent-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/bittorrent" "--cd" "/root/simgrid/simgrid/examples/msg/bittorrent" "bittorrent.tesh")
ADD_TEST(msg-bittorrent-ucontext-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/nthreads:4" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/bittorrent" "--cd" "/root/simgrid/simgrid/examples/msg/bittorrent" "bittorrent.tesh")
ADD_TEST(msg-kademlia-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/kademlia" "--cd" "/root/simgrid/simgrid/examples/msg/kademlia" "kademlia.tesh")
ADD_TEST(msg-kademlia-ucontext-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/nthreads:4" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/kademlia" "--cd" "/root/simgrid/simgrid/examples/msg/kademlia" "kademlia.tesh")
ADD_TEST(msg-migration-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/migration/migration.tesh")
ADD_TEST(msg-ptask-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/parallel_task/parallel_task.tesh")
ADD_TEST(msg-priority-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/priority/priority.tesh")
ADD_TEST(msg-actions-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/actions" "--cd" "/root/simgrid/simgrid/examples/msg/actions" "actions.tesh")
ADD_TEST(msg-icomms-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg/icomms" "--cd" "/root/simgrid/simgrid/examples/msg/icomms" "/root/simgrid/simgrid/examples/msg/icomms/peer.tesh")
ADD_TEST(msg-properties-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/properties/msg_prop.tesh")
ADD_TEST(msg-trace-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/teshsuite/msg" "--cd" "/root/simgrid/simgrid/teshsuite/msg" "trace/trace.tesh")
ADD_TEST(msg-chord-no-crosstraffic-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord.tesh")
ADD_TEST(msg-chord-no-crosstraffic-raw-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cfg" "contexts/nthreads:4" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord.tesh")
ADD_TEST(msg-chord-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord_crosstraffic.tesh")
ADD_TEST(msg-chord-raw-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cfg" "contexts/nthreads:4" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/chord" "--cd" "/root/simgrid/simgrid/examples/msg/chord" "chord_crosstraffic.tesh")
ADD_TEST(msg-bittorrent-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/bittorrent" "--cd" "/root/simgrid/simgrid/examples/msg/bittorrent" "bittorrent.tesh")
ADD_TEST(msg-bittorrent-raw-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/nthreads:4" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/bittorrent" "--cd" "/root/simgrid/simgrid/examples/msg/bittorrent" "bittorrent.tesh")
ADD_TEST(msg-kademlia-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/kademlia" "--cd" "/root/simgrid/simgrid/examples/msg/kademlia" "kademlia.tesh")
ADD_TEST(msg-kademlia-raw-parallel "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/nthreads:4" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg/kademlia" "--cd" "/root/simgrid/simgrid/examples/msg/kademlia" "kademlia.tesh")
ADD_TEST(simdag-test-simdag "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/examples/simdag" "--cd" "/root/simgrid/simgrid/examples/simdag" "/root/simgrid/simgrid/examples/simdag/test_simdag.tesh")
ADD_TEST(simdag-test-simdag2 "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/examples/simdag" "--cd" "/root/simgrid/simgrid/examples/simdag" "/root/simgrid/simgrid/examples/simdag/test_simdag2.tesh")
ADD_TEST(simdag-test-seq-access "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/examples/simdag" "--cd" "/root/simgrid/simgrid/examples/simdag" "/root/simgrid/simgrid/examples/simdag/test_simdag_seq_access.tesh")
ADD_TEST(simdag-test-typed-tasks "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/examples/simdag" "--cd" "/root/simgrid/simgrid/examples/simdag" "/root/simgrid/simgrid/examples/simdag/test_simdag_typed_tasks.tesh")
ADD_TEST(simdag-test-fail "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/simdag" "--cd" "/root/simgrid/simgrid/examples/simdag" "test_simdag_fail.tesh")
ADD_TEST(simdag-test-avail "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/simdag" "--cd" "/root/simgrid/simgrid/examples/simdag" "test_simdag_avail.tesh")
ADD_TEST(simdag-test-comm-throttling "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/examples/simdag" "--cd" "/root/simgrid/simgrid/examples/simdag" "/root/simgrid/simgrid/examples/simdag/test_simdag_comm_throttling.tesh")
ADD_TEST(simdag-test-dax "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/simdag/dax" "--cd" "/root/simgrid/simgrid/examples/simdag/dax" "smalldax.tesh")
ADD_TEST(simdag-test-dax-cycle "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/examples/simdag/dax" "--cd" "/root/simgrid/simgrid/examples/simdag/dax" "/root/simgrid/simgrid/examples/simdag/dax/simple_dax_with_cycle.tesh")
ADD_TEST(simdag-test-prop "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/examples/simdag" "--cd" "/root/simgrid/simgrid/examples/simdag" "/root/simgrid/simgrid/examples/simdag/properties/test_prop.tesh")
ADD_TEST(simdag-test-minmin-scheduling "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/simdag/scheduling" "--cd" "/root/simgrid/simgrid/examples/simdag/scheduling" "test_minmin.tesh")
ADD_TEST(simdag-test-io "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/simdag/" "--setenv" "srcdir=/root/simgrid/simgrid/" "--cd" "/root/simgrid/simgrid/examples/" "/root/simgrid/simgrid/examples/simdag/io/io.tesh")
ADD_TEST(msg-gtnets-crosstraffic-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/gtnets/gtnets-crosstraffic.tesh")
ADD_TEST(msg-gtnets-crosstraffic-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/gtnets/gtnets-crosstraffic.tesh")
ADD_TEST(msg-gtnets-crosstraffic-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "/root/simgrid/simgrid/examples/msg/gtnets/gtnets-crosstraffic.tesh")
ADD_TEST(tracing-help "/root/simgrid/simgrid/teshsuite/simdag/platforms/basic_parsing_test" "--help-tracing")
ADD_TEST(tracing-ms "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "tracing/ms.tesh")
ADD_TEST(tracing-simdag "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/examples/simdag" "--cd" "/root/simgrid/simgrid/examples/simdag" "/root/simgrid/simgrid/examples/simdag/test_simdag_tracing.tesh")
ADD_TEST(tracing-trace_platform "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "tracing/trace_platform.tesh")
ADD_TEST(tracing-user_variables "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "tracing/user_variables.tesh")
ADD_TEST(tracing-link_user_variables "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "tracing/link_user_variables.tesh")
ADD_TEST(tracing-link_srcdst_user_variables "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "tracing/link_srcdst_user_variables.tesh")
ADD_TEST(tracing-categories "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "tracing/categories.tesh")
ADD_TEST(tracing-process-migration "/root/simgrid/simgrid/bin/tesh" "--setenv" "bindir=/root/simgrid/simgrid/examples/msg" "--cd" "/root/simgrid/simgrid/examples/msg" "tracing/procmig.tesh")
ADD_TEST(graphicator "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid" "--setenv" "bindir=/root/simgrid/simgrid/bin" "--cd" "/root/simgrid/simgrid/tools/graphicator" "graphicator.tesh")
ADD_TEST(smpi-bcast-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast.tesh")
ADD_TEST(smpi-reduce-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce.tesh")
ADD_TEST(smpi-vector-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/vector.tesh")
ADD_TEST(smpi-hvector-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/hvector.tesh")
ADD_TEST(smpi-indexed-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/indexed.tesh")
ADD_TEST(smpi-struct-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/struct.tesh")
ADD_TEST(smpi-pt2pt-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/pt2pt.tesh")
ADD_TEST(smpi-compute-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/compute.tesh")
ADD_TEST(smpi-shared-thread "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:thread" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/shared.tesh")
ADD_TEST(smpi-bcast-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast.tesh")
ADD_TEST(smpi-reduce-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce.tesh")
ADD_TEST(smpi-vector-ucontex "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/vector.tesh")
ADD_TEST(smpi-hvector-ucontex "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/hvector.tesh")
ADD_TEST(smpi-indexed-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/indexed.tesh")
ADD_TEST(smpi-struct-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/struct.tesh")
ADD_TEST(smpi-pt2pt-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/pt2pt.tesh")
ADD_TEST(smpi-compute-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/compute.tesh")
ADD_TEST(smpi-shared-ucontext "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:ucontext" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/shared.tesh")
ADD_TEST(smpi-bcast-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast.tesh")
ADD_TEST(smpi-reduce-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce.tesh")
ADD_TEST(smpi-vector-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/vector.tesh")
ADD_TEST(smpi-hvector-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/hvector.tesh")
ADD_TEST(smpi-indexed-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/indexed.tesh")
ADD_TEST(smpi-struct-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/struct.tesh")
ADD_TEST(smpi-pt2pt-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/pt2pt.tesh")
ADD_TEST(smpi-compute-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/compute.tesh")
ADD_TEST(smpi-shared-raw "/root/simgrid/simgrid/bin/tesh" "--cfg" "contexts/factory:raw" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/shared.tesh")
ADD_TEST(smpi-tracing-ptp "/root/simgrid/simgrid/bin/tesh" "--cd" "/root/simgrid/simgrid/examples/smpi" "/root/simgrid/simgrid/examples/smpi/tracing/smpi_traced.tesh")
ADD_TEST(smpi-replay "/root/simgrid/simgrid/bin/tesh" "--setenv" "srcdir=/root/simgrid/simgrid/examples/smpi" "--cd" "/root/simgrid/simgrid/examples/smpi" "/root/simgrid/simgrid/examples/smpi/replay/smpi_replay.tesh")
ADD_TEST(smpi-gather-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/gather:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/gather_coll.tesh")
ADD_TEST(smpi-gather-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/gather:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/gather_coll.tesh")
ADD_TEST(smpi-gather-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/gather:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/gather_coll.tesh")
ADD_TEST(smpi-gather-coll-ompi_basic_linear "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/gather:ompi_basic_linear" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/gather_coll.tesh")
ADD_TEST(smpi-gather-coll-ompi_linear_sync "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/gather:ompi_linear_sync" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/gather_coll.tesh")
ADD_TEST(smpi-gather-coll-ompi_binomial "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/gather:ompi_binomial" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/gather_coll.tesh")
ADD_TEST(smpi-allgather-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-2dmesh "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:2dmesh" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-3dmesh "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:3dmesh" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-bruck "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:bruck" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-GB "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:GB" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-loosely_lr "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:loosely_lr" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-NTSLR "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:NTSLR" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-NTSLR_NB "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:NTSLR_NB" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-pair "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:pair" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-rdb "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:rdb" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-rhv "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:rhv" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-ring "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:ring" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-SMP_NTS "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:SMP_NTS" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-smp_simple "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:smp_simple" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-spreading_simple "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:spreading_simple" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgather-coll-ompi_neighborexchange "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgather:ompi_neighborexchange" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgather_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-GB "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:GB" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-pair "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:pair" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-ring "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:ring" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-ompi_neighborexchange "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:ompi_neighborexchange" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-ompi_bruck "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:ompi_bruck" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-mpich_rdb "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:mpich_rdb" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allgatherv-coll-mpich_ring "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allgatherv:mpich_ring" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allgatherv_coll.tesh")
ADD_TEST(smpi-allreduce-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-lr "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:lr" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-rab1 "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:rab1" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-rab2 "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:rab2" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-rab_rdb "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:rab_rdb" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-rdb "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:rdb" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-smp_binomial "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:smp_binomial" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-smp_binomial_pipeline "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:smp_binomial_pipeline" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-smp_rdb "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:smp_rdb" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-smp_rsag "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:smp_rsag" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-smp_rsag_lr "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:smp_rsag_lr" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-smp_rsag_rab "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:smp_rsag_rab" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-redbcast "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:redbcast" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll.tesh")
ADD_TEST(smpi-allreduce-coll-ompi_ring_segmented "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/allreduce:ompi_ring_segmented" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/allreduce_coll_large.tesh")
ADD_TEST(smpi-alltoall-coll-2dmesh "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:2dmesh" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-3dmesh "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:3dmesh" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-pair "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:pair" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-pair_one_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:pair_one_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-pair_light_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:pair_light_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-pair_mpi_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:pair_mpi_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-rdb "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:rdb" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-ring "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:ring" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-ring_light_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:ring_light_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-ring_mpi_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:ring_mpi_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-ring_one_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:ring_one_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-bruck "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:bruck" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-basic_linear "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:basic_linear" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoall-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoall:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoall_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-pair "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:pair" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-pair_light_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:pair_light_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-pair_mpi_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:pair_mpi_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-pair_one_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:pair_one_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-ring "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:ring" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-ring_light_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:ring_light_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-ring_mpi_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:ring_mpi_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-ring_one_barrier "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:ring_one_barrier" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-bruck "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:bruck" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-alltoallv-coll-ompi_basic_linear "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/alltoallv:ompi_basic_linear" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/alltoallv_coll.tesh")
ADD_TEST(smpi-bcast-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-arrival_pattern_aware "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:arrival_pattern_aware" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-arrival_pattern_aware_wait "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:arrival_pattern_aware_wait" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-arrival_scatter "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:arrival_scatter" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-binomial_tree "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:binomial_tree" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-flattree "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:flattree" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-flattree_pipeline "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:flattree_pipeline" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-NTSB "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:NTSB" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-NTSL "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:NTSL" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-NTSL_Isend "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:NTSL_Isend" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-scatter_LR_allgather "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:scatter_LR_allgather" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-scatter_rdb_allgather "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:scatter_rdb_allgather" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-SMP_binary "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:SMP_binary" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-SMP_binomial "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:SMP_binomial" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-SMP_linear "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:SMP_linear" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-ompi_split_bintree "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:ompi_split_bintree" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-bcast-coll-ompi_pipeline "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/bcast:ompi_pipeline" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/bcast_coll.tesh")
ADD_TEST(smpi-reduce-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-arrival_pattern_aware "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:arrival_pattern_aware" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-binomial "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:binomial" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-flat_tree "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:flat_tree" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-NTSL "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:NTSL" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-scatter_gather "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:scatter_gather" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-ompi_chain "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:ompi_chain" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-ompi_binary "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:ompi_binary" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-ompi_basic_linear "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:ompi_basic_linear" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-ompi_binomial "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:ompi_binomial" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce-coll-ompi_in_order_binary "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce:ompi_in_order_binary" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_coll.tesh")
ADD_TEST(smpi-reduce_scatter-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce_scatter:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_scatter_coll.tesh")
ADD_TEST(smpi-reduce_scatter-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce_scatter:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_scatter_coll.tesh")
ADD_TEST(smpi-reduce_scatter-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce_scatter:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_scatter_coll.tesh")
ADD_TEST(smpi-reduce_scatter-coll-ompi_basic_recursivehalving "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce_scatter:ompi_basic_recursivehalving" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_scatter_coll.tesh")
ADD_TEST(smpi-reduce_scatter-coll-ompi_ring "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce_scatter:ompi_ring" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_scatter_coll.tesh")
ADD_TEST(smpi-reduce_scatter-coll-mpich_noncomm "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce_scatter:mpich_noncomm" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_scatter_coll.tesh")
ADD_TEST(smpi-reduce_scatter-coll-mpich_pair "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce_scatter:mpich_pair" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_scatter_coll.tesh")
ADD_TEST(smpi-reduce_scatter-coll-mpich_rdb "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/reduce_scatter:mpich_rdb" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/reduce_scatter_coll.tesh")
ADD_TEST(smpi-scatter-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/scatter:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/scatter_coll.tesh")
ADD_TEST(smpi-scatter-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/scatter:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/scatter_coll.tesh")
ADD_TEST(smpi-scatter-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/scatter:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/scatter_coll.tesh")
ADD_TEST(smpi-scatter-coll-ompi_basic_linear "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/scatter:ompi_basic_linear" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/scatter_coll.tesh")
ADD_TEST(smpi-scatter-coll-ompi_binomial "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/scatter:ompi_binomial" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/scatter_coll.tesh")
ADD_TEST(smpi-barrier-coll-default "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/barrier:default" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/barrier_coll.tesh")
ADD_TEST(smpi-barrier-coll-ompi "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/barrier:ompi" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/barrier_coll.tesh")
ADD_TEST(smpi-barrier-coll-mpich "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/barrier:mpich" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/barrier_coll.tesh")
ADD_TEST(smpi-barrier-coll-ompi_basic_linear "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/barrier:ompi_basic_linear" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/barrier_coll.tesh")
ADD_TEST(smpi-barrier-coll-ompi_tree "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/barrier:ompi_tree" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/barrier_coll.tesh")
ADD_TEST(smpi-barrier-coll-ompi_bruck "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/barrier:ompi_bruck" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/barrier_coll.tesh")
ADD_TEST(smpi-barrier-coll-ompi_recursivedoubling "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/barrier:ompi_recursivedoubling" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/barrier_coll.tesh")
ADD_TEST(smpi-barrier-coll-ompi_doublering "/root/simgrid/simgrid/bin/tesh" "--cfg" "smpi/barrier:ompi_doublering" "--cd" "/root/simgrid/simgrid/teshsuite/smpi" "/root/simgrid/simgrid/teshsuite/smpi/barrier_coll.tesh")
ADD_TEST(tesh-simdag-full-links01 "/root/simgrid/simgrid/teshsuite/simdag/platforms/basic_parsing_test" "/root/simgrid/simgrid/teshsuite/simdag/platforms/two_clusters.xml" "FULL_LINK")
ADD_TEST(tesh-simdag-full-links02 "/root/simgrid/simgrid/teshsuite/simdag/platforms/basic_parsing_test" "/root/simgrid/simgrid/teshsuite/simdag/platforms/two_clusters_one_name.xml" "FULL_LINK")
ADD_TEST(tesh-simdag-one-link-g5k "/root/simgrid/simgrid/teshsuite/simdag/platforms/basic_parsing_test" "/root/simgrid/simgrid/examples/platforms/g5k.xml" "ONE_LINK")
ADD_TEST(msg-icomms-waitany "/root/simgrid/simgrid/examples/msg/icomms/peer3" "/root/simgrid/simgrid/examples/msg/icomms/small_platform.xml" "/root/simgrid/simgrid/examples/msg/icomms/deployment_peer05.xml")
ADD_TEST(test-xbt-log "/root/simgrid/simgrid/testsuite/xbt/log_usage")
ADD_TEST(test-xbt-graphxml "/root/simgrid/simgrid/testsuite/xbt/graphxml_usage" "/root/simgrid/simgrid/testsuite/xbt/graph.xml")
ADD_TEST(test-xbt-heap "/root/simgrid/simgrid/testsuite/xbt/heap_bench")
ADD_TEST(test-surf-lmm "/root/simgrid/simgrid/testsuite/surf/lmm_usage")
ADD_TEST(test-surf-maxmin "/root/simgrid/simgrid/testsuite/surf/maxmin_bench")
ADD_TEST(test-surf-usage "/root/simgrid/simgrid/testsuite/surf/surf_usage" "--cfg=path:/root/simgrid/simgrid/testsuite/surf/" "platform.xml")
ADD_TEST(test-surf-usage2 "/root/simgrid/simgrid/testsuite/surf/surf_usage2" "--cfg=path:/root/simgrid/simgrid/testsuite/surf/" "platform.xml")
ADD_TEST(test-surf-trace "/root/simgrid/simgrid/testsuite/surf/trace_usage" "--cfg=path:/root/simgrid/simgrid/testsuite/surf/")
ADD_TEST(testall "/root/simgrid/simgrid/src/testall")
SUBDIRS(examples/java)
SUBDIRS(examples/java/async)
SUBDIRS(examples/java/bittorrent)
SUBDIRS(examples/java/chord)
SUBDIRS(examples/java/cloud)
SUBDIRS(examples/java/commTime)
SUBDIRS(examples/java/io)
SUBDIRS(examples/java/kademlia)
SUBDIRS(examples/java/master_slave_bypass)
SUBDIRS(examples/java/master_slave_kill)
SUBDIRS(examples/java/masterslave)
SUBDIRS(examples/java/migration)
SUBDIRS(examples/java/mutualExclusion)
SUBDIRS(examples/java/pingPong)
SUBDIRS(examples/java/priority)
SUBDIRS(examples/java/startKillTime)
SUBDIRS(examples/java/suspend)
SUBDIRS(examples/java/tracing)
SUBDIRS(examples/lua)
SUBDIRS(examples/msg)
SUBDIRS(examples/msg/actions)
SUBDIRS(examples/msg/bittorrent)
SUBDIRS(examples/msg/chainsend)
SUBDIRS(examples/msg/chord)
SUBDIRS(examples/msg/cloud)
SUBDIRS(examples/msg/energy/e1)
SUBDIRS(examples/msg/energy/e2)
SUBDIRS(examples/msg/energy/e3)
SUBDIRS(examples/msg/gpu)
SUBDIRS(examples/msg/gtnets)
SUBDIRS(examples/msg/icomms)
SUBDIRS(examples/msg/io)
SUBDIRS(examples/msg/kademlia)
SUBDIRS(examples/msg/masterslave)
SUBDIRS(examples/msg/mc)
SUBDIRS(examples/msg/migration)
SUBDIRS(examples/msg/ns3)
SUBDIRS(examples/msg/parallel_task)
SUBDIRS(examples/msg/pastry)
SUBDIRS(examples/msg/pmm)
SUBDIRS(examples/msg/priority)
SUBDIRS(examples/msg/properties)
SUBDIRS(examples/msg/semaphores)
SUBDIRS(examples/msg/sendrecv)
SUBDIRS(examples/msg/start_kill_time)
SUBDIRS(examples/msg/suspend)
SUBDIRS(examples/msg/token_ring)
SUBDIRS(examples/msg/tracing)
SUBDIRS(examples/scala)
SUBDIRS(examples/scala/master_slave_bypass)
SUBDIRS(examples/scala/master_slave_kill)
SUBDIRS(examples/scala/masterslave)
SUBDIRS(examples/simdag)
SUBDIRS(examples/simdag/dax)
SUBDIRS(examples/simdag/dot)
SUBDIRS(examples/simdag/goal)
SUBDIRS(examples/simdag/io)
SUBDIRS(examples/simdag/metaxml)
SUBDIRS(examples/simdag/properties)
SUBDIRS(examples/simdag/scheduling)
SUBDIRS(examples/smpi)
SUBDIRS(examples/smpi/MM)
SUBDIRS(examples/xbt)
SUBDIRS(teshsuite/msg)
SUBDIRS(teshsuite/msg/storage)
SUBDIRS(teshsuite/msg/trace)
SUBDIRS(teshsuite/simdag)
SUBDIRS(teshsuite/simdag/availability)
SUBDIRS(teshsuite/simdag/network)
SUBDIRS(teshsuite/simdag/network/mxn)
SUBDIRS(teshsuite/simdag/network/p2p)
SUBDIRS(teshsuite/simdag/partask)
SUBDIRS(teshsuite/simdag/platforms)
SUBDIRS(teshsuite/simix)
SUBDIRS(teshsuite/smpi)
SUBDIRS(teshsuite/smpi/mpich3-test)
SUBDIRS(teshsuite/smpi/mpich3-test/attr)
SUBDIRS(teshsuite/smpi/mpich3-test/coll)
SUBDIRS(teshsuite/smpi/mpich3-test/comm)
SUBDIRS(teshsuite/smpi/mpich3-test/datatype)
SUBDIRS(teshsuite/smpi/mpich3-test/group)
SUBDIRS(teshsuite/smpi/mpich3-test/init)
SUBDIRS(teshsuite/smpi/mpich3-test/pt2pt)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/coll)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/comm)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/datatype)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/ext)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/init)
SUBDIRS(teshsuite/smpi/mpich3-test/f77/pt2pt)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/coll)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/datatype)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/init)
SUBDIRS(teshsuite/smpi/mpich3-test/f90/pt2pt)
SUBDIRS(teshsuite/xbt)
SUBDIRS(testsuite/surf)
SUBDIRS(testsuite/xbt)
SUBDIRS(tools)
SUBDIRS(tools/graphicator)
SUBDIRS(tools/tesh)
